# Numpy Library

In [1]:
l1=[1,2,3]

In [2]:
l2=[10,20,30]

In [3]:
l=[l1,l2]

In [4]:
l

[[1, 2, 3], [10, 20, 30]]

In [5]:
l[0]

[1, 2, 3]

In [6]:
l[1]

[10, 20, 30]

In [7]:
import numpy as np

We can store multiple values in single variable

In [8]:
arr1=np.array(l1)

In [9]:
arr1

array([1, 2, 3])

In [10]:
arr2=np.array(l2)

In [11]:
arr2

array([10, 20, 30])

In [12]:
arr3=np.array(l)

In [13]:
arr3

array([[ 1,  2,  3],
       [10, 20, 30]])

In [14]:
arr3.dtype

dtype('int64')

In [15]:
arr1.shape

(3,)

In [16]:
arr2.shape

(3,)

In [17]:
arr3.shape

(2, 3)

In [18]:
arr=np.array([[1,2],[2,1],[6,7]])

In [19]:
arr

array([[1, 2],
       [2, 1],
       [6, 7]])

In [20]:
arr.dtype

dtype('int64')

In [21]:
arr.shape

(3, 2)

In [22]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [23]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
a.shape

(3, 3)

In [25]:
a.dtype

dtype('int64')

In [26]:
a[0]

array([1, 2, 3])

In [27]:
a[-1]

array([7, 8, 9])

In [28]:
a[1,2]

6

In [29]:
a[0,2]

3

In [30]:
a[2,0]

7

In [31]:
a[0,0]

1

In [32]:
a[2,1]

8

In [33]:
a[1,2]=10

In [34]:
a

array([[ 1,  2,  3],
       [ 4,  5, 10],
       [ 7,  8,  9]])

In [35]:
a[0,1]

2

In [36]:
a[1,0]

4

In [37]:
a[1,0]=40

In [38]:
a[0,0]=100

# 

In [39]:
a

array([[100,   2,   3],
       [ 40,   5,  10],
       [  7,   8,   9]])

In [40]:
a[:]

array([[100,   2,   3],
       [ 40,   5,  10],
       [  7,   8,   9]])

In [41]:
a[:,2]

array([ 3, 10,  9])

In [42]:
a[1,:]

array([40,  5, 10])

In [43]:
b=np.array([range(1,11)])

In [44]:
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [45]:
b.shape

(1, 10)

In [46]:
d=np.array(range(1,11))

In [47]:
d.shape

(10,)

In [48]:
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
c=np.arange(1,11)

In [50]:
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
c.shape

(10,)

In [52]:
e=np.array(range(14,141,14))

In [53]:
e

array([ 14,  28,  42,  56,  70,  84,  98, 112, 126, 140])

In [54]:
e_17=np.arange(17,171,17)

In [55]:
e_17

array([ 17,  34,  51,  68,  85, 102, 119, 136, 153, 170])

In [56]:
f=np.arange(16)

In [57]:
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [58]:
f[7]

7

In [59]:
f[3:7]

array([3, 4, 5, 6])

# Concept of slicing

In [60]:
x=np.arange(0,9)

In [61]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [62]:
y=np.arange(9)

In [63]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [64]:
y.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [65]:
np.arange(3,3)

array([], dtype=int64)

In [66]:
a=np.array(range(5,61,5))

In [67]:
a

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [68]:
len(a)

12

In [69]:
a.reshape(6,2)

array([[ 5, 10],
       [15, 20],
       [25, 30],
       [35, 40],
       [45, 50],
       [55, 60]])

In [70]:
a.reshape(4,3)

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [50, 55, 60]])

In [71]:
a.reshape(1,12)

array([[ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60]])

In [72]:
a.reshape(12,1)

array([[ 5],
       [10],
       [15],
       [20],
       [25],
       [30],
       [35],
       [40],
       [45],
       [50],
       [55],
       [60]])

In [73]:
a.reshape(3,2,2)

array([[[ 5, 10],
        [15, 20]],

       [[25, 30],
        [35, 40]],

       [[45, 50],
        [55, 60]]])

In [74]:
a.reshape(3,2,2).base

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [75]:
b=a.reshape(3,4)

In [76]:
b

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60]])

In [77]:
b[1,1]

30

In [78]:
a.reshape(3,4)[1,1]

30

In [79]:
a.reshape(3,4)[1:1]

array([], shape=(0, 4), dtype=int64)

In [80]:
b[1:1]

array([], shape=(0, 4), dtype=int64)

In [81]:
b[0:1]

array([[ 5, 10, 15, 20]])

In [82]:
b[1]

array([25, 30, 35, 40])

In [83]:
b[0:2]

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40]])

In [84]:
b[2]

array([45, 50, 55, 60])

In [85]:
b[:,1]

array([10, 30, 50])

In [86]:
b[0:1]

array([[ 5, 10, 15, 20]])

In [87]:
b[1:0]

array([], shape=(0, 4), dtype=int64)

In [88]:
b[:1]

array([[ 5, 10, 15, 20]])

In [89]:
b

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60]])

In [90]:
b[[1,1]+[1,2]]

array([[25, 30, 35, 40],
       [25, 30, 35, 40],
       [25, 30, 35, 40],
       [45, 50, 55, 60]])

In [91]:
b[1:1]

array([], shape=(0, 4), dtype=int64)

In [92]:
b[1:2,1:3]                                   #.....................1   1:2 is row and 1:3 for columns

array([[30, 35]])

In [93]:
b[[1,1],[1,2]]                               #......................2

array([30, 35])

In [94]:
b[1,1:3]                                     #......................3

array([30, 35])

In [95]:
b

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60]])

In [96]:
b[2:3,2:4]

array([[55, 60]])

In [97]:
30,35,50,55

(30, 35, 50, 55)

In [98]:
b[1:3,1:3]                 #[row,column],,,1:3 rows and 1:3 columns

array([[30, 35],
       [50, 55]])

In [99]:
b[1:4,1:3]

array([[30, 35],
       [50, 55]])

In [100]:
b[1:4,1:5]

array([[30, 35, 40],
       [50, 55, 60]])

In [101]:
b[1,1:3]

array([30, 35])

In [102]:
b[[1,2],[1,2]]

array([30, 55])

In [103]:
b[1,2]

35

b

In [104]:
b[[1,2],[2,3]]

array([35, 60])

In [105]:
b

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60]])

In [106]:
b[[0,1],[1,1]]

array([10, 30])

In [107]:
b[[0,2],[1,1]]

array([10, 50])

In [108]:
b[[0,1],[1,2]]

array([10, 35])

In [109]:
b[[1,2],[1,2]]

array([30, 55])

In [1]:
b = "Hello, World!"
print(b[2:5])

llo


In [2]:
b[7:8]

'W'

In [3]:
a = "I wish that i could go there"

In [5]:
a[-5:]

'there'