In [ ]:
import numpy as np

In [1]:
a=np.arange(18)

NameError: name 'np' is not defined

In [3]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [4]:
a.reshape(9,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17]])

In [5]:
b=np.array('0'*100)

In [6]:
b

array('0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
      dtype='<U100')

In [7]:
c=np.zeros([10,10])

In [8]:
c

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
c[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
c[1]+1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
for i in c:
    print(i)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [44]:
for i in c:
    c[i]=i

IndexError: arrays used as indices must be of integer (or boolean) type

In [45]:
c

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [46]:
for i in range(10):
    c[i]=i

In [47]:
c

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [48]:
a=range(10)

In [49]:
for i in a:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [50]:
c=np.zeros([10,10])

In [51]:
c

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [52]:
for i in range(10):
    c[:,i]=i                                           #..............1

In [53]:
c

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [59]:
d=np.transpose(c)                                        #..............1

In [60]:
d

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [61]:
for i in range(10):
    c[i,:]=i                                           #..............2

In [62]:
c

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

# Fancy Indexing

In [26]:
c

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [27]:
c[0:1]

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [28]:
c[1:0]

array([], shape=(0, 10), dtype=float64)

In [32]:
c[2]

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [33]:
d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [30]:
d[2]

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [31]:
d[[2,4,6]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.]])

In [34]:
a=np.arange(50)

In [35]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [36]:
b=a.reshape(10,5)

In [65]:
b                                              #.....................1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [63]:
x=np.arange(50).reshape(10,5)

In [66]:
x                                              #.....................2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [70]:
y=x.T

In [71]:
y

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [72]:
z=np.dot(x,y)

In [73]:
z

array([[   30,    80,   130,   180,   230,   280,   330,   380,   430,
          480],
       [   80,   255,   430,   605,   780,   955,  1130,  1305,  1480,
         1655],
       [  130,   430,   730,  1030,  1330,  1630,  1930,  2230,  2530,
         2830],
       [  180,   605,  1030,  1455,  1880,  2305,  2730,  3155,  3580,
         4005],
       [  230,   780,  1330,  1880,  2430,  2980,  3530,  4080,  4630,
         5180],
       [  280,   955,  1630,  2305,  2980,  3655,  4330,  5005,  5680,
         6355],
       [  330,  1130,  1930,  2730,  3530,  4330,  5130,  5930,  6730,
         7530],
       [  380,  1305,  2230,  3155,  4080,  5005,  5930,  6855,  7780,
         8705],
       [  430,  1480,  2530,  3580,  4630,  5680,  6730,  7780,  8830,
         9880],
       [  480,  1655,  2830,  4005,  5180,  6355,  7530,  8705,  9880,
        11055]])

In [75]:
z.shape

(10, 10)

In [76]:
e=np.arange(10).reshape(5,2)

In [77]:
e

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [78]:
f=np.sqrt(e)

In [79]:
f

array([[0.        , 1.        ],
       [1.41421356, 1.73205081],
       [2.        , 2.23606798],
       [2.44948974, 2.64575131],
       [2.82842712, 3.        ]])

In [80]:
g=np.exp(e)

In [11]:
g

NameError: name 'g' is not defined

In [45]:
import numpy as np                                         #import

In [13]:
from numpy.random import randn                             #import

In [14]:
randn(4)

array([ 0.89903732,  0.92071748,  1.23335642, -0.093057  ])

In [15]:
np.random.randint(1,50,size=10)

array([ 8, 40, 31, 28, 34, 34, 49, 10, 40,  5])

In [16]:
np.random.randint(5)
    

1

In [20]:
np.random.randint(4,10)

6

In [31]:
np.random.randint(-5,5,size=4)

array([ 4, -1, -1,  2])

In [32]:
np.random.randint(-5,5)

-2

In [41]:
import random                                               #import

In [42]:
random.randint(-5,5)

-1

In [47]:
random.randint(5,90,size=5)

TypeError: randint() got an unexpected keyword argument 'size'

In [34]:
from numpy.random import randint                            #import

In [35]:
randint(5,90,size=5)

array([16,  6, 22,  8, 60])

In [29]:
randint(5,90)

9

In [48]:
randint(5,90,5)

array([23, 25, 76, 89, 19])

In [52]:
randn(1,4)

array([[ 0.77967698,  0.86252008, -0.64490807,  1.2799802 ]])

# Binary function of array

In [53]:
a=np.arange(10)

In [54]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
b=np.arange(11,21)

In [56]:
b

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [58]:
c=randn(10)

In [59]:
c

array([ 0.72419812,  0.26326503, -0.96920557, -1.60821902, -0.54040889,
       -0.80782809,  1.78525111,  0.04116026, -1.31039227, -0.68505919])

In [66]:
d=randn(10)

In [67]:
d

array([-0.18880183,  0.92596221, -0.31913023, -0.83079885, -0.02935479,
        0.32929602,  0.74873233,  1.16779581,  1.59151889, -0.62645956])

In [70]:
e=c+d
print(e)

[ 0.5353963   1.18922724 -1.2883358  -2.43901786 -0.56976368 -0.47853207
  2.53398344  1.20895607  0.28112662 -1.31151875]


In [71]:
np.add(c,c)

array([ 1.44839624,  0.52653006, -1.93841113, -3.21643803, -1.08081778,
       -1.61565619,  3.57050222,  0.08232053, -2.62078454, -1.37011838])

In [72]:
c+c

array([ 1.44839624,  0.52653006, -1.93841113, -3.21643803, -1.08081778,
       -1.61565619,  3.57050222,  0.08232053, -2.62078454, -1.37011838])

In [74]:
np.maximum(c,d)

array([ 0.72419812,  0.92596221, -0.31913023, -0.83079885, -0.02935479,
        0.32929602,  1.78525111,  1.16779581,  1.59151889, -0.62645956])

In [77]:
np.minimum(c,d)

array([-0.18880183,  0.26326503, -0.96920557, -1.60821902, -0.54040889,
       -0.80782809,  0.74873233,  0.04116026, -1.31039227, -0.68505919])